"""empty message

Revision ID: 1b45f57776c
Revises: 48c52a2c084
Create Date: 2015-10-16 16:46:59.785905

"""

# revision identifiers, used by Alembic.
revision = '1b45f57776c'
down_revision = '48c52a2c084'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('role', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_role_default'), 'role', ['default'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_default'), table_name='role')
    op.drop_column('role', 'permissions')
    op.drop_column('role', 'default')
    ### end Alembic commands ###
