"""empty message

Revision ID: 3fd0ce5cd8e
Revises: 33ccdc2a0bd
Create Date: 2015-10-20 16:53:51.885014

"""

# revision identifiers, used by Alembic.
revision = '3fd0ce5cd8e'
down_revision = '33ccdc2a0bd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_hash')
    ### end Alembic commands ###
