"""empty message

Revision ID: 43aecab57b8
Revises: 5704472630b
Create Date: 2015-10-21 11:54:16.477823

"""

# revision identifiers, used by Alembic.
revision = '43aecab57b8'
down_revision = '5704472630b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'body_html')
    ### end Alembic commands ###
