"""empty message

Revision ID: 48c52a2c084
Revises: None
Create Date: 2015-10-12 12:40:47.116624

"""

# revision identifiers, used by Alembic.
revision = '48c52a2c084'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmed')
    ### end Alembic commands ###
