"""add title_url

Revision ID: f2f5d773aa
Revises: 2aaa66781b8
Create Date: 2015-10-31 16:09:43.538274

"""

# revision identifiers, used by Alembic.
revision = 'f2f5d773aa'
down_revision = '2aaa66781b8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('url_title', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_post_url_title'), 'post', ['url_title'], unique=False)
    op.create_unique_constraint(None, 'post_tag', ['tag_id', 'post_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_tag', type_='unique')
    op.drop_index(op.f('ix_post_url_title'), table_name='post')
    op.drop_column('post', 'url_title')
    ### end Alembic commands ###
